# Generated by Django 5.2.1 on 2025-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
