# Generated by Django 5.2.1 on 2025-06-28 23:43

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_asesoria_zoom_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage, upload_to='projects_images/', verbose_name='Image'),
        ),
    ]
