# Generated by Django 5.2.1 on 2025-06-28 22:47

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage, upload_to='posts_images', verbose_name='Image'),
        ),
    ]
